### ISSUE TITLE
Can't parse stream-error data into json

### ISSUE THREAD

**Issue by simlist** [fanout/django-eventstream#107]
When I try to parse the data from a stream-error event into json I get the following error:
```
Uncaught SyntaxError: Expected property name or '}' in JSON at position 1
```
The error is caused by the strings in the data object having single quotes.
```
{'condition': 'forbidden', 'text': 'Permission denied to channels: orders', 'channels': ['orders']}
```
If I do `JSON.parse(event.data.replaceAll("'", '"'))` to replace the single quotes with double quotes, then there is no error.

**Comment by jkarneges** [comment]
Thanks for the report! This is now fixed.

**Comment by simlist** [comment]
Thank you very much! Great package.
