### ISSUE TITLE
 Client keep sending requests even if it receives a refuse answer

### ISSUE THREAD

**Issue by housUnus** [fanout/django-eventstream#112]
Clients that don't satisfy some conditions must not receive messages, but even if the client connection is refused, it keeps sending a request which is very annoying.
"HTTP GET /events/_admins/ 400 [0.00, 127.0.0.1:51739]"
"HTTP GET /events/_admins/ 200 [0.00, 127.0.0.1:51739]"

My channel Manager:
class MyChannelManager(DefaultChannelManager):
    def can_read_channel(self, user, channel):
        # require auth for prefixed channels
        if channel.startswith('_') and user is None:
            return False
        return Tr

**Comment by jkarneges** [comment]
Hi @housUnus, this is really up to the client code. It should close the connection after receiving a stream-error, for example: https://github.com/fanout/django-eventstream/blob/master/examples/time/timeapp/templates/timeapp/home.html#L38-L39

**Comment by housUnus** [comment]
Thanks this resolved the issue.
