### ISSUE TITLE
What is the difference between evenstream and websockets?

### ISSUE THREAD

**Issue by alielmorsy** [fanout/django-eventstream#127]
I saw this library on Git Hub while searching and I got surprised by how it works.
 So what is the difference between it and WebSockets?

**Comment by zesameri** [comment]
Both Django EventStream (using Server-Sent Events) and Channels (for WebSockets) are viable options for implementing real-time communication in your Django application. 

**Django EventStream (Server-Sent Events):**

**Pros:**
1. **Simplicity:** Server-Sent Events (SSE) are relatively straightforward to implement, especially if you're already familiar with HTTP. SSE uses a unidirectional flow of data from the server to the client.
2. **Wide Browser Support:** SSE is natively supported in most modern browsers, making it accessible for a broad audience without requiring additional libraries or frameworks.
3. **Automatic Reconnection:** SSE automatically handles reconnections in case of network interruptions, providing a seamless experience for users.

**Cons:**
1. **One-way Communication:** SSE is unidirectional, meaning the server can only send data to the client. If you need bidirectional communication (e.g., sending messages from the client to the server), you'd need to implement another mechanism for that.
2. **Limited to Text Data:** SSE supports only plain text data, so if you need to send more complex data structures, you might need to serialize and parse them on both ends.
3. **Less Control:** SSE offers less control over the connection compared to WebSockets. You cannot easily close or manipulate the connection from the client side.

**Channels (WebSockets):**

**Pros:**
1. **Bidirectional Communication:** WebSockets enable full-duplex communication, meaning both the server and the client can send data at any time. This is useful for scenarios where the client needs to interact with the server in real time.
2. **Efficient Data Transfer:** WebSockets allow you to send binary data efficiently, making it suitable for streaming more complex data types like images.
3. **Full Control:** With WebSockets, you have greater control over the connection, including opening, closing, and managing the connection state.

**Cons:**
1. **Complexity:** WebSockets can be more complex to implement than SSE, especially if you're new to the technology. Channels, as a package for Django, abstracts some of this complexity but might still require a learning curve.
2. **Browser Compatibility:** While most modern browsers support WebSockets, you might encounter issues with older browsers or certain network configurations.

Here is a video that explains it as well: [Don't Use Websockets (Until You Try This…)](https://www.youtube.com/watch?v=6QnTNKOJk5A&ab_channel=CodeWithRyan)
