### ISSUE TITLE
ModuleNotFoundError: No module named 'channels.http'

### ISSUE THREAD

**Issue by JSL107** [fanout/django-eventstream#132]
Hello
I tried to use SSE with django channels but got an error.

# **This** is my settings.py
![image](https://github.com/fanout/django-eventstream/assets/95362504/c2e16f28-d011-497e-b442-7bd35b9d7867)

# **This is My Python Package version**
![image](https://github.com/fanout/django-eventstream/assets/95362504/012cdb6f-37be-4fed-a767-7fed87875f7a)
![image](https://github.com/fanout/django-eventstream/assets/95362504/9453e1d0-8d15-4e37-9b09-35d07b79cb8a)

### why am i Get this Error? 
`ModuleNotFoundError: No module named 'channels.http'`

### If the issue is caused by the version, what method should I use to implement SSE?

**Comment by paul-english** [comment]
Try using `channels==3.0.5` for now.

**Comment by SatoTake2019** [comment]
worked at channels==3.0.5, Thank you paul-english

**Comment by JSL107** [comment]
Thank you for your Comment i'm fixed it !
