### ISSUE TITLE
CORS Error: How can we allow multiple origins

### ISSUE THREAD

**Issue by sau0409** [fanout/django-eventstream#133]
As per document we can only give single value for EVENTSTREAM_ALLOW_ORIGIN, but in my case I need to allow one more origin. If I try changing EVENTSTREAM_ALLOW_ORIGIN = "*", I get another cors error.

![Screenshot from 2023-11-03 18-14-10](https://github.com/fanout/django-eventstream/assets/64318068/30004235-99e5-45fa-84fc-933f787189f5)

**Comment by jkarneges** [comment]
Hmm, yeah this isn't possible. I suppose the header needs to be dynamically determined based on the request.

One idea is to set the `Access-Control-Allow-Origin` response header to the value of the request's `Host` header if `EVENTSTREAM_ALLOW_ORIGIN` is set to an asterisk. What do you think?

**Comment by jkarneges** [comment]
Update: the latest version now uses async views instead of channels, which means CORS configuration can now be managed with django-cors-headers.
