### ISSUE TITLE
TypeError: url() got an unexpected keyword argument 'channels'

### ISSUE THREAD

**Issue by vnahmias** [fanout/django-eventstream#14]
hello i am configuring the project following your explanations but at some point i got this error : 

```
TypeError: url() got an unexpected keyword argument 'channels'
```

triggered by this line : 
`url(r'^events/', AuthMiddlewareStack(URLRouter(django_eventstream.routing.urlpatterns)), channels=['test']),`

i have no other clues cause i am beginning on this project, i've checked my other routing.py file which calls this one, installed channels and django-eventstream

**Comment by jkarneges** [comment]
Thanks for the report! The problem is some of the examples were passing `url` kwargs incorrectly.

Instead of `channels=['test']` it needs to be `{'channels':['test']}`.

The readme has been corrected.

**Comment by vnahmias** [comment]
Thanks to you :)
