### ISSUE TITLE
Question: Why Django 5+?

### ISSUE THREAD

**Issue by Sonictherocketman** [fanout/django-eventstream#144]
I'd like to use this project with 4.2 (LTS) as I prefer to just hop Django LTSs. I tested it using 4.2 and it seems to work just fine. Is there any reason why this requires 5.0+ currently that I might have missed?

**Comment by jkarneges** [comment]
Async streaming response bodies and/or their accounting don't work quite right before Django 5. I don't remember the exact problems, but if you're using ASGI and not fronting with Pushpin/Fastly then you might notice connections getting disconnected early, or disconnections not being detected.
