### ISSUE TITLE
IMPORTANT !! - Publish problem

### ISSUE THREAD

**Issue by enzofrnt** [fanout/django-eventstream#149]
Hi,

Please take a quick look, I need this module urgently! Thank you!

There is an issue in the latest release: the templates folder, which contains necessary files for browsableAPI, is not included in the released build. See:
<img width="696" alt="image" src="https://github.com/fanout/django-eventstream/assets/63660254/b3eb650d-72df-458a-b911-b3d50080630b">

In result, the browsableAPI is broke.

I don't know how you're publishing it, but that, not doing it properly.
Thank you!!

**Comment by enzofrnt** [comment]
Some CSS fix may also be needs on the browsable API

**Comment by enzofrnt** [comment]
CSS is fix here :
#150

**Comment by enzofrnt** [comment]
Hi, @jkarneges this fix is important.. The REST part of the module is not usable.

**Comment by jkarneges** [comment]
Ok I think I finally fixed this in 5.2.3. Let me know if it's still not right.

**Comment by enzofrnt** [comment]
Everything now fine
