### ISSUE TITLE
Messaages not sending from storage when client back

### ISSUE THREAD

**Issue by onyx-zup** [fanout/django-eventstream#158]
EVENTSTREAM_STORAGE_CLASS = "django_eventstream.storage.DjangoModelStorage"

1. client connected, listener added
![image](https://github.com/user-attachments/assets/62873e5e-8ccf-4962-ab56-7d66f2183f5e)

this time storage have last message # 38
![image](https://github.com/user-attachments/assets/acb39812-76fd-41b0-b6a7-00afb39a0ff0)

2. sending ones  while client connected -message queued and sent to client - works fine 
![image](https://github.com/user-attachments/assets/58d79619-05b4-4d9d-a894-b017c9a1a3ac)
message at client side
![image](https://github.com/user-attachments/assets/ba5f027d-4879-4256-9cce-1f0b33c9ad26)
last message in storage # 39
![image](https://github.com/user-attachments/assets/aaf75f57-b988-4cda-864e-926e65ad6e11)

Everything is ok and as expected. now client closes browser tab:
3. client closed browser tab, listener removed
![image](https://github.com/user-attachments/assets/3c400920-a009-4a1b-8a0d-c3d0ae2bfdab)

4. SENDING on same channel:
![image](https://github.com/user-attachments/assets/af8dd75e-46ec-468a-823b-49a91bfa4a1e)
no messages queued, and this is ok, because no listener connected, but saved to models:
![image](https://github.com/user-attachments/assets/89344ecf-8869-45c4-8c7f-0afc012af530)

last message now is # 40, it just stored, not sent

5. Now im expecting when client comes back and connects to the same sse url (of course it will have new listener id, but the same sse url), eventsource should look for not sent but stored messages, and finally sent it to client.
**6. But it never happen. message # 40 will not be delivered, never ever.**

**Comment by onyx-zup** [comment]
django-eventstream documentation:

> If clients get disconnected, intermediate proxies go down, or your own server goes down or crashes at any time, even mid-publish, the stream will automatically be repaired.

After that, am i wrong thinking that unsent messages will be pushed to client when it connects to particular sse channel?

**Comment by jkarneges** [comment]
The `lastEventId` query parameter on the SSE request can be used to tell django-evenstream to replay events starting from a certain ID. If you're able to store the last ID somewhere (for example in a cookie), you could use it the next time the page is loaded.

That said, DjangoModelStorage is not meant to be used for restoring state if the user closes the page and comes back later. It is meant for resolving temporary problems while the page is still loaded in the browser. This is why django-eventstream's examples use conventional means to obtain the current state during page load, and the SSE stream is only used for new events going forward by configuring it with `get_current_event_id()`.

**Comment by onyx-zup** [comment]
thanks. where i can find docs on eventrequest ?

**Comment by jkarneges** [comment]
There are no reference docs, so you'd have to read the code. `EventRequest` has very few public fields though. There's basically the `lastEventId` query param, the `Last-Event-ID` header, and whatever `get_channels_for_request` does (customizable). The rest are private for GRIP proxy mode.

**Comment by onyx-zup** [comment]
thanx
