### ISSUE TITLE
Default number of limit on channel numbers

### ISSUE THREAD

**Issue by LihengGong** [fanout/django-eventstream#16]
From [source code](https://github.com/fanout/django-eventstream/blob/master/django_eventstream/eventrequest.py), I can see that the default number of limit for the maximum channel number is 10.

My question is: If I do not overwrite this value, does that mean there are only as many as 10 channels?

```python
def __init__(self, http_request=None, channel_limit=10, view_kwargs={})
```

**Comment by LihengGong** [comment]
I raised this issue because when testing with the chat example, I can see that Django stops responding if there are more than 6 rooms(http://localhost:9000/room1?user=1; ...; http://localhost:9000/room6?user=1) or more than 6 users(http://localhost:9000/room1?user=1; ....; http://localhost:9000/r1?user=6).

**Comment by jkarneges** [comment]
Yes. This is a conservative default that should probably be turned into a setting so you don't have to write your own view to change the value.

**Comment by LihengGong** [comment]
Thanks. Close this issue for now.
