### ISSUE TITLE
sending events from outside the ASGI request context

### ISSUE THREAD

**Issue by h1nk** [fanout/django-eventstream#21]
Is it possible to be able to use the `send_event` function from outside the ASGI execution context, i.e. from a manage command or something?

**Comment by jkarneges** [comment]
Hi, this can be done if connection handling is delegated to Fanout/Pushpin. Then, `send_event` can be called from other processes, including management commands or the shell.

See https://github.com/fanout/django-eventstream#multiple-instances-and-scaling
