### ISSUE TITLE
'Access-Control-Allow-Credentials' not included in Settings.py - Causing CORS error

### ISSUE THREAD

**Issue by RickyV33** [fanout/django-eventstream#25]
Digging through your source code, it looks like there's a settings.py parameter for setting an allowed origin (EVENTSTREAM_ALLOW_ORIGIN). There doesn't seem to be an option for setting 'Access-Control-Allow-Credentials' to `True`, though. I can open up a PR for this if you'd like.

**Comment by jkarneges** [comment]
Sure, that would be great.

Ideally something like `django-cors-headers` could be made to work so that we don't need our own CORS code, but mixing such libraries with ASGI is tricky.

**Comment by RickyV33** [comment]
Awesome. Would adding functionality similar to how you have EVENTSTREAM_ALLOW_ORIGIN operating now be okay in the interim?

**Comment by jkarneges** [comment]
Yep!
