### ISSUE TITLE
Which file do i put the send_event info into?

### ISSUE THREAD

**Issue by Bluetip33** [fanout/django-eventstream#29]
Hi,
I have got to the to the part, where you place the send_event info into a file but i don't know which file?.

Thanks.

**Comment by jkarneges** [comment]
Any file. Call `send_event()` whenever you need to send an event. For example, in a view handler.

**Comment by Bluetip33** [comment]
Hi, 
Sorry i'm new to Django and still don't understand, can a view handler be the views.py. And if i put it in there, it would go in a function which needs to return a HttpRepsonse but the send_event('test', 'message', {'text': 'hello world'}) doesn't.

Thanks for any help.

**Comment by jkarneges** [comment]
Exactly. For example, in the [chat example](https://github.com/fanout/django-eventstream/blob/master/examples/chat/chat/views.py), you can see the `messages` function which calls `send_event`.

**Comment by Bluetip33** [comment]
Thanks for the help, checking it out now.
