### ISSUE TITLE
EventsConsumer doesn't work with channels >=2.1.6

### ISSUE THREAD

**Issue by vfernandezmartinez** [fanout/django-eventstream#31]
When using Django Channels >= 2.1.6, EventsConsumer doesn't work. Upon sending a GET request to the SSE endpoint (e.g. with curl), no response data is received back and the connection is left open. EventsConsumer never replies and no events are delivered. This didn't happen with channels 2.1.5, where it works fine.

The implementation of AsyncHttpConsumer was changed in 2.1.6, which seems to be the cause of this issue. As a result, EventsConsumer.disconnect() gets called and the consumer is left in this dangling state. A dirty workaround is to await the self.stream task at the end of EventsConsumer.handle().

**Comment by jkarneges** [comment]
Indeed (https://github.com/django/channels/issues/1249). I'll look at implementing a workaround soon, or pin the dependency to 2.1.5.

**Comment by jkarneges** [comment]
Released new version with workaround.
