### ISSUE TITLE
django_grip>=2.0.0,<3'

### ISSUE THREAD

**Issue by prowald** [fanout/django-eventstream#42]
As Django Version 3 was released django.utils.decorators is deprecated.
While installig django-eventstream django-grip version 2.2 will be used, which leads to following error.

django.utils.decorators
ImportError: cannot import name 'available_attrs' from 'django.utils.decorators' (/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py)

install_requires should include version 3 of django_grip.

Best regards

**Comment by jkarneges** [comment]
Thanks for the report. This is now fixed.
