### ISSUE TITLE
Is it possible to update subscribed channels?

### ISSUE THREAD

**Issue by pierre-lucas40** [fanout/django-eventstream#48]
Hello,

My problem is that I want my clients to receive data from the server but the channels they have subscribed to may change over time. So, I've looked into django_grip and grip_control but I'm not sure if it is possible to update subscribed channels of a SSE connection as you would with a Websocket. 
Or should I use websocket ? My issue would then be passing the authentication token.

Thank you very much for your help.

Have a great day !

**Comment by jkarneges** [comment]
Hi,

Changing the channels of an active SSE connection might be possible using a custom ChannelManager and publishing a hint action, though I've not tested this.

However, my recommendation is for the client to explicitly say what it is interested in. If the client wants to listen to something else, it can create a new SSE connection and close the old.

If you expect the client to change its interests very often, then a WebSockets-based protocol could potentially be more efficient for something like that. However, django-eventstream only supports SSE, and for most apps that is fine.

**Comment by pierre-lucas40** [comment]
Thank you very much for you fast answer. 

I still don't really understand how the hint action would work. For the websocket transport, this is done by sending control messages to Pushpin. But I don't see how I can send this kind of messages for an active SSE connection (Would this question be more appropriate on Pushpin's repository?). If it's not possible, I'll use the websocket protocol. 

Thanks again !

**Comment by jkarneges** [comment]
Publish actions described here: https://pushpin.org/docs/usage/#publish-actions

Basically, when you publish a hint action to any HTTP streams, Pushpin will make HTTP requests to the backend on behalf of clients, for instruction about what to do next. This would cause django-eventstream to reevaluate their channels. Clients will be subscribed to whatever channels django-eventstream returns, and this process would be invisible to clients (they'd have no idea their channels got changed).

Thus, you could potentially change the channels of existing connections by making sure the channel manager's `get_channels_for_request` method returns something different when Pushpin makes the requests in reaction to the hint. The hint would need to be sent through `django-grip` (the library used by django-eventstream behind the scenes) and you'd need to declare your own format (`HttpStreamFormat` from the `gripcontrol` library doesn't support sending hints yet) but this should be fairly easy to do.

If this thread deviates from away from django-eventstream, then yes the Pushpin repository would be more appropriate (or perhaps [django-grip](https://github.com/fanout/django-grip)).

**Comment by pierre-lucas40** [comment]
Your answer is very clear, I'll look into this. Thank you very much !
Have a great day !
