### ISSUE TITLE
About a minute's delay between send_event and pushpin logging the published event

### ISSUE THREAD

**Issue by foucdeg** [fanout/django-eventstream#62]
I've recently set up pushpin as a GRIP proxy in front of my existing app configured as instructed.

Things seem to work well, except that events seem to take a long time to be published. There seems to be a delay between 10 seconds and 2 minute between the moment `send_event` returns, and the moment when pushpin prints log about the published event. After pushpin has logged the event, the subscribed client almost immediately receives the event.

What could cause such a delay?

**Comment by foucdeg** [comment]
Never mind, docker misconfiguration on my end. Sorry.

**Comment by timomeara** [comment]
> Never mind, docker misconfiguration on my end. Sorry.
hi @foucdeg- i’m suddenly getting the same thing, what was the miss config?
