### ISSUE TITLE
Connected clients

### ISSUE THREAD

**Issue by paolodina** [fanout/django-eventstream#69]
Is it possible to get the connected clients for a channel? I'd need to get related clients info (ip, number of connected clients etc).

Basically, what I'd really need is, if I have more than n connected client I should be able to limit the number of outgoing messages. Tangential reference ticket: #67 (any opinion on that?)

**Comment by jkarneges** [comment]
By limit the number of outgoing messages, do you mean limit the rate? Are you sending some kind of info to clients on an interval, and you want to slow down the interval when there are lots of clients?

**Comment by paolodina** [comment]
Sorry I've not been clear.

Yes I'm sending info to clients at periodic intervals. My issue is that the data size is ~100kb, sent every 5 seconds to each client. Suppose there are 1000 connected clients for a day, and well it's a good amount of outgoing bandwidth at the end of the month.

So I was looking for a way to limit the outgoing traffic and initially thought to handle that limiting the number of targets client to the first n... but first I'll surely try to put a reverse proxy with gzip in front (like you suggested in #67).

About the number of connected clients, I'd be interested anyway to know how many clients are receiving the message at a certain time, possibly with some extra info (like the IP of these clients). I wonder if it's possible.

Thanks!

**Comment by jkarneges** [comment]
That is a lot of data to send with such frequency. If it's for a user interface, I think either the user would be overwhelmed with content or much of the data isn't used. I wonder if you could send less data? Unless it's multimedia data like graphics, but in that case it would probably already be compressed.

Django-eventstream doesn't provide a way to get the concurrent client count or IPs, but you might be able to make an ASGI middleware to do this. Another way is to use Pushpin in front of your app, which emits this kind of information from its [stats socket](https://pushpin.org/docs/advanced/#stats-socket).

**Comment by jkarneges** [comment]
That is a lot of data to send with such frequency. If it's for a user interface, I think either the user would be overwhelmed with content or much of the data isn't used. I wonder if you could send less data? Unless it's multimedia data like graphics, but in that case it would probably already be compressed.

Django-eventstream doesn't provide a way to get the concurrent client count or IPs, but you might be able to make an ASGI middleware to do this. Another way is to use Pushpin in front of your app, which emits this kind of information from its [stats socket](https://pushpin.org/docs/advanced/#stats-socket).

**Comment by paolodina** [comment]
It's crypto currency data that the backend reads from the exchanges APIs (every ~5 secs) and sends to the frontend where users apply filters.

I'll try first with the ASGI middleware then with Pushpin, thanks for both the ideas. Eventually I'll post the middleware here.
