### ISSUE TITLE
Django 3.2 Changes Default pk Field Type

### ISSUE THREAD

**Issue by Zoidmania** [fanout/django-eventstream#75]
From the [docs](https://docs.djangoproject.com/en/3.2/topics/db/models/#automatic-primary-key-fields):

Starting with Django 3.2, the built-in ID/PK field type is `BigAutoField`.

> `id = models.BigAutoField(primary_key=True)`
> ...
> In older versions, auto-created primary key fields were always AutoFields.

This causes a new migration requirement for this package:

```python
operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventcounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
```

The initial model/migration will need to be updated to use BigAutoField, or you can [set default id field type in the app config](https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.default_auto_field).

How do you want to handle this? Are pull requests preferable?

**Comment by jkarneges** [comment]
Hmm, well whatever we do, hopefully it can be backwards compatible. Open to pull requests.

**Comment by squarism** [comment]
Backward compatible to which Django version(s)?
