### ISSUE TITLE
Is the Werkzeug dependency still valid?

### ISSUE THREAD

**Issue by OmenApps** [fanout/django-eventstream#77]
I see that the project has a dependency of 'Werkzeug>=0.12,<1'. Is this still valid?

I don't see any imports of Werkzeug within the repo, and version 1 of Werkzeug is nearly two years old.

Just curious where the need for this dependency comes from? Thanks!

**Comment by jkarneges** [comment]
Thanks for pointing this out. I suspect there was some Werkzeug code that got moved to django-grip (a lower level lib) but the dependency wasn't removed from this project. That is now done.

Note that django-grip still does depend on Werkzeug.
