### ISSUE TITLE
Deprecated usage for MiddlewareMixin

### ISSUE THREAD

**Issue by Schlepptop** [fanout/django-eventstream#84]
As of [this commit](https://github.com/django/django/commit/4bb30fe5d598a7acd2a3055c5e66224cf42a75e9) to the Django codebase, this will no longer work, as the `MiddlewareMixin` will require an argument for `get_request`:

https://github.com/fanout/django-eventstream/blob/57d4456f5da85e7f0139cd9ccfdfc8581bd42726/django_eventstream/consumers.py#L137

**Comment by fmgoncalves** [comment]
There is a PR open to deal with this https://github.com/fanout/django-eventstream/pull/82

**Comment by jkarneges** [comment]
The fix has been merged.
