### ISSUE TITLE
Connection Error when running examples

### ISSUE THREAD

**Issue by bhargav95** [fanout/django-eventstream#9]
I followed the instructions given in the Readme for both the basic and the chat examples, but I continuously get "Connected" and "Connection Lost" messages. I am running it on an Ubuntu machine.

**Comment by bhargav95** [comment]
Thank you, that works!

**Comment by bhargav95** [comment]
For the chat example, Fanout works, but Pushpin does not. I got http://localhost:7999 set up, but even after running the web server, it shows the Apache Ubuntu homepage instead of the actual website.
I am trying to run `pushpin --route="* localhost:8000"` with sudo, will that cause any errors?

**Comment by jkarneges** [comment]
Did you install Pushpin via apt? If so, it's probably already running. In that case edit `/etc/pushpin/routes` to contain `* localhost:8000`.

**Comment by bhargav95** [comment]
Thanks, that worked.
Yes, I had installed it using apt.
